puts "The students of my cohort at Makers Academy"
puts "----------"
puts "Jamie Patel"
puts "Faezrah Rizalman"
puts "Dr. Hannibal Lecter"
puts "Darth Vader"
puts "Nurse Ratched"
puts "Michael Corleone"
puts "The Alien"
puts "Terminator"
puts "Freddy Kruger"
puts "The Joker"
